import { Badge } from "@dsj/ui";
import { getStatusLabel } from "../lib/labels";

const toneMap: Record<string, "slate" | "blue" | "green" | "amber" | "red"> = {
  DRAFT: "slate",
  READY_TO_SEND: "amber",
  PARTIALLY_SENT: "amber",
  READY_FOR_SIGNING: "amber",
  SIGNING_READY: "amber",
  PARTIALLY_SIGNED: "blue",
  SIGNED: "green",
  SUBMITTED: "amber",
  IN_APPROVAL: "amber",
  APPROVED: "blue",
  SUSPENDED: "amber",
  CLOSED: "green",
  ANNULLED: "red",
  SUPERSEDED: "slate",
  FINAL: "blue",
  VOIDED: "red",
  ARCHIVED: "slate",
  ACTIVE: "green",
  EXPIRING: "amber",
  EXPIRED: "red",
  EXPIRING_SOON: "amber",
  ASSIGNED: "blue",
  OPENED: "blue",
  ACKNOWLEDGED: "amber",
  IN_PROGRESS: "blue",
  COMPLETED: "green",
  OVERDUE: "red",
  AVAILABLE: "blue",
  NOT_STARTED: "slate",
  PASSED: "green",
  FAILED: "red",
  account_enabled: "green",
  account_disabled: "slate",
  queued: "blue",
  processing: "amber",
  sent: "green",
  failed: "red",
  skipped: "slate",
  PENDING: "amber",
  VERIFIED: "green",
  REJECTED: "red",
  admitted: "green",
  limited: "amber",
  blocked: "red",
  draft: "slate",
  pending_precheck: "amber",
  missing_documents: "red",
  pending_approval: "amber",
  on_approval: "amber",
  approved: "blue",
  signed: "green",
  active: "green",
  suspended: "amber",
  extended: "blue",
  closed: "green",
  rejected: "red",
  cancelled: "red",
  annulled: "red",
  replaced: "slate",
  expired: "red",
  archived: "slate",
  inactive: "slate",
};

export function StatusBadge({ value }: { value: string }) {
  return <Badge tone={toneMap[value] ?? "slate"}>{getStatusLabel(value)}</Badge>;
}
